# Generated by Django 4.2.1 on 2023-05-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('release_date', models.DateField(null=True)),
                ('price', models.FloatField(null=True)),
                ('image', models.ImageField(default='default_header.jpg', upload_to='')),
            ],
        ),
    ]
