# Generated by Django 4.2.1 on 2023-05-26 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(null=True)),
                ('release_date', models.DateField(null=True)),
                ('image', models.TextField(null=True)),
            ],
            options={
                'db_table': 'app',
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('rank', models.IntegerField(primary_key=True, serialize=False)),
                ('last_week_rank', models.IntegerField()),
                ('peak_in_game', models.IntegerField()),
                ('app', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rank', to='steamdb.app')),
            ],
            options={
                'db_table': 'rank',
            },
        ),
    ]
