# Generated by Django 4.2.2 on 2023-06-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamdb', '0002_app_capsule_image_app_discount_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
