# Generated by Django 4.2.1 on 2023-05-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamdb', '0002_alter_game_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameName',
            fields=[
                ('appid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'steamdb_getname',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('rank', models.IntegerField(primary_key=True, serialize=False)),
                ('appid', models.IntegerField()),
                ('last_week_rank', models.IntegerField()),
                ('peak_in_game', models.IntegerField()),
            ],
            options={
                'db_table': 'steamdb_gameinfo',
            },
        ),
    ]
