# Generated by Django 4.2.1 on 2023-05-28 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steamdb', '0002_alter_rank_app'),
        ('steamdb', '0003_gamename_info'),
    ]

    operations = [
    ]
