# Generated by Django 4.2 on 2023-06-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamdb', '0003_app_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='short_description',
            field=models.CharField(max_length=130, null=True),
        ),
    ]
