# Generated by Django 4.2 on 2023-06-15 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steamdb', '0004_app_short_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='final_price',
            new_name='final_formatted',
        ),
    ]
