# Generated by Django 4.2 on 2023-06-15 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steamdb', '0005_rename_final_price_app_final_formatted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='final_formatted',
            new_name='price_overview',
        ),
    ]
