# Generated by Django 4.2 on 2023-06-15 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steamdb', '0006_rename_final_formatted_app_price_overview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='price_overview',
            new_name='final',
        ),
    ]
