# Generated by Django 4.2 on 2023-06-15 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steamdb', '0007_rename_price_overview_app_final'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='final',
            new_name='final_price',
        ),
    ]
