# Generated by Django 4.2 on 2023-06-15 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steamdb', '0008_rename_final_app_final_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='final_price',
            new_name='final_formatted',
        ),
    ]
