# Generated by Django 4.2 on 2023-05-08 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='Animation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=70)),
                ('original_title', models.CharField(default='', max_length=70)),
                ('company', models.CharField(default='', max_length=70)),
                ('rated', models.CharField(default='', max_length=70)),
                ('broadcasted_date', models.CharField(default='', max_length=70)),
                ('chapters', models.CharField(default='', max_length=70)),
                ('story', models.TextField(default='', max_length=256)),
                ('img', models.TextField(default='', max_length=256)),
                ('genre', models.ManyToManyField(related_name='animations', to='polls.genre')),
            ],
            options={
                'db_table': 'animations',
            },
        ),
    ]
